### ISSUE TITLE
Several suggestions

### ISSUE THREAD

**Issue by daattali** [calligross/ggthemeassist#48] opened 2016-03-18 00:07 UTC
First of all, good job and thank you for this addin, it's great. I really like it.

I have several suggestions and instead of opening many issues and spamming you, I'll just list them all here:

- [x] When clicking on the addin from the addins menu without having any plot selected in the editor, you get an obscure error.  Instead, it'd be helpful if you wrote an informative error message like "Please highlight a ggplot2 plot before selecting this addin"

- [x] It'd be nice if I could run the addin from the commandline instead of having to click on it with the mouse. Ideally, `ggThemeAssist(plot)` would have the same effect as highlighting `plot` and clicking on the addin

- [ ] Just a suggestion: since you're making heavy use of colour select inputs, maybe consider using the [`shinyjs::colourInput()`](http://daattali.com/shiny/colourInput/)

- [x] In the "Title and label" tab, under "Labels", it's unclear that "Colour" and "Fill" should take a variable rather than an actual colour.  Maybe add the word "variable" to make it clear? 

- [x] For some reason when I make a simple ggplot and add a title with `+ ggtitle("foo")`, the size of the title in the gadget appears as 1.2 (which makes it unreadable, it's tiny)

- [ ] If the plot doesn't have a legend, maybe disable or don't show the "Legend" tab

- [x] In the legend tab, it'd be nice to have an option for "Remove legend" since that's a fairly common thing to do as well

Just some features that I think would enhance this awesome addin :)

**Comment by calligross** [comment] 2016-03-18 06:00
Thanks a lot, any hints from users are appreciated.

I will look into your suggestions during the weekend. Regarding your last point (removing the legend), that's already possible. Just select None as position, but that shows that maybe "remove" is more clear to the user.

**Comment by daattali** [comment] 2016-03-18 06:04
Ah, I suppose I didn't look closely enough.  I personally would find it nicer to have a separate checkboxInput that lets you clear it, but it's up to you if you think it makes more sense.  Disclaimer: I'm the author of shinyjs, so I usually recommend people use the colourInput when I see a usecase..

**Comment by calligross** [comment] 2016-03-18 06:12
I know, and I looked into it last weekend. That's also a great enhancement!

I didn't use it for ggThemeAssist (yet), because I had a lack of time to try it in detail. 

Sure, a check box would be more obvious, but at the moment we try to figure out, what a good UI would look like. Another check box would have the trade off, that we need another UI element.

Today a project ends, which kept me really busy the last weeks. Can't wait to try several things for ggThemeAssist which came to my mind in the last couple of days.

**Comment by daattali** [comment] 2016-03-18 06:16
Yep, UI is not a fun thing to design.... literally half my time making shiny apps is making the UI intuitive.. 

One other thing you might benefit from is something that I don't know how to do yet and I've been looking for answers.  A way to have a UI element be shared across different tabs, such as the plot in your case. In regular shiny apps it's easy, but with miniUI I couldn't find a way to do it.  So I saw your solution was to just have the plot repeated in every tab.  I'm going to ask Joe about it soon, but would love to see if you find a way around that

**Comment by calligross** [comment] 2016-03-18 12:40
- For some reason when I make a simple ggplot and add a title with + ggtitle("foo"), the size of the title in the gadget appears as 1.2 (which makes it unreadable, it's tiny)

Are you using the latest version? I think this behaviour should have been fixed last weekend.

**Comment by daattali** [comment] 2016-03-18 19:28
I realize now this only happens if I add a `theme_bw()`. For example `ggplot(mtcars, aes(wt, mpg)) + geom_point() +  theme_bw(20) + ggtitle("foo")`

**Comment by calligross** [comment] 2016-03-19 10:53
Sorry, I still can't reproduce it. Are you sure, you are using the latest version from master? This should have been fixed with ec418bd.

<img width="890" alt="bildschirmfoto 2016-03-19 um 11 44 34" src="https://cloud.githubusercontent.com/assets/15100661/13898114/239be266-edc8-11e5-945d-79ac629e01b3.png">

**Comment by daattali** [comment] 2016-03-19 10:56
I was using CRAN version.  If you fixed it on GitHub version, then I trust that it's fixed

**Comment by calligross** [comment] 2016-03-19 10:57
Ahhhh, ok. That explains a lot :-)

**Comment by ottlngr** [comment] 2016-03-19 16:15
`shinyjs::colourInput()` is a cool feature but I think at least some (if not many) users would miss the colour names...

**Comment by daattali** [comment] 2016-03-23 12:04
@calligross I've updated the original post to change the bullet points into a checkmark-able list since I noticed you started tackling a few of these things, so you can check them off if it helps.

@ottlngr I see what you mean. colourInput will in fact happily take "coral2" as an initial value, but you're right that it will return a HEX value and not a name.  Actually... you gave me a good idea, `colourInput` should have the option to return a name!

**Comment by daattali** [comment] 2016-03-23 14:08
FYI you can now use `colourInput(..., returnName = TRUE)` and it will return back an actual R colour instead of HEX values.  You can use `colourInput(..., returnName = TRUE, palette = "limited", allowedCols = c("black", "blue", "cyan", "magenta"))` if you want to just show certain colours.  If you want to use it

**Comment by calligross** [comment] 2016-03-25 11:15
I'm closing here for now. I'm still considering using colourInput(), but haven't made a final decision for now.

**Closed by calligross** 2016-03-25 11:15 UTC
